version: '2.1'
services:
  nginx:
    image: 'nginx:stable-alpine'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './nginx/entrypoint.bash:/entrypoint.bash:ro'
    depends_on:
      - engine
    volumes_from:
      - 'engine:ro'
    entrypoint: /entrypoint.bash
    ports:
      - '${PROJECTPORTPREFIX}080:80'
      - '${PROJECTPORTPREFIX}081:81'
  engine:
    build: ./engine/
    volumes:
      - './engine/php.ini:/usr/local/etc/php/php.ini:ro'
      - '../../:/var/www/html/project:rw'
    environment:
      - DEV_UID
      - DEV_GID
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=gobelins
      - DB_USERNAME=gobelins
      - DB_PASSWORD=password
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - SESSION_DRIVER=redis
      - CACHE_DRIVER=redis
  db:
    image: 'postgres:9.6-alpine'
    environment:
      - POSTGRES_USER=gobelins
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gobelins
    volumes:
      - './db/mn.datasource.database.dump:/mn.datasource.database.dump:ro'
    ports:
      - '${PROJECTPORTPREFIX}435:5432'
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '${PROJECTPORTPREFIX}180:1080'
    links:
      - engine
  adminer:
    image: 'adminer:latest'
    ports:
      - '${PROJECTPORTPREFIX}084:8080'
  redis:
    image: 'redis:latest'
    depends_on:
      - engine
  redisadmin:
    image: 'rediscommander/redis-commander:latest'
    environment:
      - 'REDIS_HOSTS=default:redis:6379'
    ports:
      - '${PROJECTPORTPREFIX}083:8081'
