db:
  type: postgresql:10
  disk: 2048
  configuration:
    extensions:
      - plpgsql
    databases:
      - gobelins
    endpoints:
      gobelins:
        privileges:
          gobelins: admin

cache:
  type: redis:5.0
